import { timingSafeEqual, createHmac, pbkdf2Sync } from 'crypto';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

export const SESSION_COOKIE = 'ilf_admin_session';
const SESSION_MAX_AGE_SECONDS = 8 * 60 * 60; // 8 hours

function safeEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  if (bufA.length !== bufB.length) return false;
  return timingSafeEqual(bufA, bufB);
}

/**
 * ADMIN_PASSWORD_HASH format: pbkdf2:<iterations>:<saltHex>:<hashHex>
 * Generated by the local admin-password-tool.html — never derived from a
 * plaintext password typed into this codebase or chat.
 * Uses ':' rather than '$' as the delimiter: Next.js's built-in env loader
 * treats '$' as a variable-substitution character and silently truncates
 * the value at the first one, which is not obvious from the outside.
 */
export function verifyPassword(password: string): boolean {
  const stored = process.env.ADMIN_PASSWORD_HASH;
  if (!stored) return false;

  const parts = stored.split(':');
  if (parts.length !== 4 || parts[0] !== 'pbkdf2') return false;
  const [, iterationsStr, saltHex, hashHex] = parts;
  const iterations = parseInt(iterationsStr, 10);
  if (!Number.isFinite(iterations) || iterations <= 0) return false;

  const derived = pbkdf2Sync(password, Buffer.from(saltHex, 'hex'), iterations, hashHex.length / 2, 'sha256');
  return safeEqual(derived.toString('hex'), hashHex);
}

function sign(payload: string): string {
  const secret = process.env.ADMIN_SESSION_SECRET;
  if (!secret) throw new Error('ADMIN_SESSION_SECRET is not set.');
  return createHmac('sha256', secret).update(payload).digest('hex');
}

export function createSessionToken(): string {
  const payload = Buffer.from(JSON.stringify({ iat: Date.now() })).toString('base64url');
  return `${payload}.${sign(payload)}`;
}

export function verifySessionToken(token: string | undefined): boolean {
  if (!token) return false;
  const [payload, signature] = token.split('.');
  if (!payload || !signature) return false;

  let expected: string;
  try {
    expected = sign(payload);
  } catch {
    return false;
  }
  if (!safeEqual(signature, expected)) return false;

  try {
    const { iat } = JSON.parse(Buffer.from(payload, 'base64url').toString());
    if (typeof iat !== 'number') return false;
    return Date.now() - iat < SESSION_MAX_AGE_SECONDS * 1000;
  } catch {
    return false;
  }
}

export const sessionCookieOptions = {
  httpOnly: true,
  secure: process.env.NODE_ENV === 'production',
  sameSite: 'lax' as const,
  path: '/',
  maxAge: SESSION_MAX_AGE_SECONDS,
};

export async function requireAdmin(): Promise<void> {
  const store = await cookies();
  const token = store.get(SESSION_COOKIE)?.value;
  if (!verifySessionToken(token)) {
    redirect('/admin/login');
  }
}
